In [18]:
import torch
import torch.nn as nn
import numpy as np

In [3]:
# Problem 1
block1 = nn.Sequential(nn.Conv2d(1,1,3))
net = nn.Sequential(block1)
net(torch.randn(1,1,3,3)).shape

torch.Size([1, 1, 1, 1])

In [4]:
# Problem 2
block2 = nn.Sequential(nn.Conv2d(1,1,3))
net = nn.Sequential(block2,block2)
net(torch.randn(1,1,5,5)).shape

torch.Size([1, 1, 1, 1])

In [9]:
# Problem 3
block3 = nn.Sequential(nn.Conv2d(1,1,5))
net = nn.Sequential(block3)
net(torch.randn(1,1,5,5)).shape

torch.Size([1, 1, 1, 1])

In [11]:
# Problem 4
block4 = nn.Sequential(nn.Conv2d(1,1,5))
net = nn.Sequential(block4,block4)
net(torch.randn(1,1,9,9)).shape

torch.Size([1, 1, 1, 1])

In [14]:
# Problem 5
block51 = nn.Sequential(nn.Conv2d(1,1,3))
block52 = nn.Sequential(nn.MaxPool2d(4))
net = nn.Sequential(block51,block52,block51)
net(torch.randn(1,1,14,14)).shape

torch.Size([1, 1, 1, 1])

In [17]:
# Problem 6
block6 = nn.Sequential(nn.Conv2d(1,1,5),nn.MaxPool2d(2))
net = nn.Sequential(block6,block6,block6,block6)
net(torch.randn(1,1,77,76)).shape

torch.Size([1, 1, 1, 1])

In [22]:
# Problem 7
w=2
b=0
x=[20,10,0]
y=[1,0,-1]
y_p = [0,0,0]
for i in range(len(x)-1):
    y_p[i] = np.tanh(2*x[i] + b)
print(y_p)


[1.0, 1.0, 0]


In [30]:
# Problem 8
error=0
for i in range(len(y)):
    error = (y_p[i]-y[i])**2 + error 
print(error)

2.0


In [37]:
def model(x_in,w_in,b_in):
    return torch.tanh(w_in*x_in+b_in)
def loss_func(y_p,y_in):
    return (y_p-y_in)**2
    

In [41]:
# Problem 10
theta = torch.tensor([2.0, 0.0], requires_grad=True)
a=0.1
optim = torch.optim.SGD([theta],lr=a)
for i in range(len(x)):
    error = loss_func(model(x[i],*theta),y[i])
    optim.zero_grad()
    error.backward()
    optim.step()
    print(theta.grad)
# Problem 11
print(theta)

tensor([0., 0.])
tensor([0., 0.])
tensor([0., 2.])
tensor([ 2.0000, -0.2000], requires_grad=True)
